### ISSUE TITLE
Batchid Pattern

### ISSUE THREAD

**Issue by blrunner** [Netflix/metacat#166]
Hello, this is Jaehwa.

I have quick question about Metacat.

I have read in several articles that Netflix uses the following `batchid` pattern to avoid eventual consistency issues.

* Never delete existing output in partitions.
* Each job inserts a unique sub-partition called "batchid".

If I store partitions in the Hive table using Metcat, does Metacat create the `batchid`?

Best Regards,
Jaehwa

**Comment by ajoymajumdar** [comment]
Hello Jaehwa,
No, Metacat does not create the batchid sub-partition. The batchid pattern logic is contained in another client module(not open sourced) that is integrated with Pig/Spark, S3 and Metacat.
Metacat adds the partitions in the metastore as requested by the client module.

**Comment by blrunner** [comment]
Hello @ajoymajumdar ,
Thanks for your kind answer. I also checked that source codes don't support it a few days ago. Thank you again for making sure once again. :-)
