### ISSUE TITLE
./gradlew metaPorts failed due to missing metacat-functional-tests/build/logs/metacat directory

### ISSUE THREAD

**Issue by smoy** [Netflix/metacat#213]
I ran the following commands

./gradlew clean build
./gradlew metacatPorts

It keeps failing with 

ERROR: for metacattestcluster_metacat_1  Cannot create container for service metacat: lstat /nail/home/smoy/external/metacat/metacat-functional-tests/build/logs
/metacat: not a directory

ERROR: for metacat  Cannot create container for service metacat: lstat /nail/home/smoy/external/metacat/metacat-functional-tests/build/logs/metacat: not a direc
tory

So I work around the problem by making the directory ahead of metacatPorts as follow

mkdir -p /nail/home/smoy/external/metacat/metacat-functional-tests/build/logs/metacat

Hope this help others who ran into the same problem

**Comment by ajoymajumdar** [comment]
Thanks for the workaround @smoy. 
It looks like you have a mounting issue from the containers to your local system. You might not have your local directories shared with docker. Please see https://docs.docker.com/docker-for-mac/osxfs/#namespaces.
