### ISSUE TITLE
Teradata connector

### ISSUE THREAD

**Issue by brosenfi** [Netflix/metacat#239]
Hello - apologies for entering this as an issue (it's really just a question) - I asked this on the google group metacatoss, but I'm not sure anyone is checking that.  I'm wondering since Teradata is referenced in the readme, which connector should be used for it?  Obviously it allows jdbc connections, but jdbc isn't by itself a valid connector.

**Comment by ajoymajumdar** [comment]
Actually we do not have a connector for teradata. We had a connector internally which used proprietary code. You are right, you can add a connector extending the jdbc connector and use it.

**Comment by brosenfi** [comment]
Thanks Ajoy - really appreciate you answering that.
