### ISSUE TITLE
Setting the metacat.usermetadata.config.location property

### ISSUE THREAD

**Issue by adelgadillouplift** [Netflix/metacat#267]
I've set the catalog folder location property in the application.yml file, but I can't find where to set the metacat.usermetadata.config.location; running a find function on the source files doesn't find any matching property name.

**Comment by ajoymajumdar** [comment]
You can either set the config metacat.usermetadata.config.location in the application.yml file or pass it as JAVA_OPTS. For example: https://github.com/Netflix/metacat/blob/master/metacat-functional-tests/metacat-test-cluster/docker-compose.yml. You can see that the tomcat docker image is started using the configs passed as java options. The docker functional tests use the following usermetadata file - https://github.com/Netflix/metacat/blob/master/metacat-functional-tests/metacat-test-cluster/etc-metacat/usermetadata.properties. You can create the usermetadata database using (only for mysql) -
https://github.com/Netflix/metacat/blob/master/metacat-metadata-mysql/src/test/resources/sql/prepare-test.sql
