### ISSUE TITLE
exec ./gradlew clean build error

### ISSUE THREAD

**Issue by RoyalFeng** [Netflix/metacat#274]
Hi ajoymajumdar.Firstly,Thanks to your open source code, I am glad to explore metacat, but when I follow your readme,I have met some errors. I have try some solutions in these issues, but it did not work to me, can you help me? The error is shown in the following figure. Thank you
![image](https://user-images.githubusercontent.com/3387165/42762599-528a77fe-8943-11e8-9c3a-ed1cb829eb3b.png)

**Comment by RoyalFeng** [comment]
Hi ajoymajumdar:
      I have build successful, but I can not configure the data catalog, when I  request http:localhost:8080/mds/v1/catalog, the error is 404, can you share some doc with us? Thanks to your reply

**Comment by sabarnwa** [comment]
@RoyalFeng .. the application.yml file exists as a resource under metacat-main project.
You can add the catalog as well as usermetadata config location in the file.

**Comment by RoyalFeng** [comment]
@sabarnwa Thanks for your reply,can i contact you with email?

**Comment by RoyalFeng** [comment]
@sabarnwa  I configure metacat.usermetdata.config.location in the application.yml, and new mkdir /etc/catalog, I put two files( sample and mysql-56-db.properties) in /etc/catalog. Is it right?

**Comment by sabarnwa** [comment]
@RoyalFeng .. yes.. it looks fine. You can contact me via mail.

**Comment by RoyalFeng** [comment]
@sabarnwa  Thank for your reply , my own e-mail is royalfy@gmail.com, can you contact me by email?or you tell me your email (sorry,I can not find your email)

**Comment by RoyalFeng** [comment]
@sabarnwa  take the war file under metacat-war/build/libs directory and rename metacat-1.2.0-SNAPSHOT.war to ROOT.war? But Tomcat/webapp/ has root file, this will conflict,so can you tell me detailed  
steps?Thank you

**Comment by sabarnwa** [comment]
<img width="424" alt="screen shot 2018-07-18 at 3 17 27 pm" src="https://user-images.githubusercontent.com/16033766/42874034-bbc5743e-8a9d-11e8-8b3e-84bc92034436.png">

**Comment by RoyalFeng** [comment]
@sabarnwa Thanks for your reply. When I replace the ROOT.war and I start the tomcat,localhost:8080 is "can not find localhost page", The 8080 port is not configurated . so I do not know how to do. I think the building procedure has occurred some errors, and is the metacat project under /etc? Thank you

**Comment by RoyalFeng** [comment]
@sabarnwa I can not find mds directory in tomcat/webapp/. ROOT's directory structure is shown in the following figure. please help me see whether it is right. Thank you very much.
![image](https://user-images.githubusercontent.com/3387165/42878362-65b5f862-8abf-11e8-9de9-42a047b8dfcf.png)

**Comment by sabarnwa** [comment]
Can you check with this url: http://localhost:8080/swagger-ui.html#/
or "curl -X GET --header 'Accept: */*' 'http://localhost:8080/mds'"

**Comment by RoyalFeng** [comment]
@sabarnwa  Thanks for your reply, If you do not mind ,can i contact with you via mail? I think this will be fast and efficient, Thank you very much.

**Comment by RoyalFeng** [comment]
@sabarnwa  In my opinion, if I can access http://localhost:8080/mds, "mds" directory must be under the directory "tomcat/webapp/ROOT/", is it right? But in my  scene, I can not find mds in ROOT directory.
