### ISSUE TITLE
presto integration?

### ISSUE THREAD

**Issue by tooptoop4** [Netflix/metacat#289]
is presto a source of metadata for metacat? or can presto query data from metacat?

can you provide some sample configs for presto integration?

**Comment by tooptoop4** [comment]
I have connected presto to the metacat thrift port ie 12001 but then in presto when i query that catalog it just looks like what presto gets from querying hive catalog (ie port 9083). What extra should presto be able to see from the metacat thrift port?

**Comment by ajoymajumdar** [comment]
Yes, it will show the same. Today we do not sync the business metadata that Metacat stores into the table/partition params but in the future we might. 
The idea behind exposing the thrift API in Metacat is to make it a central gateway for all data stores. This way we can incorporate common patterns/features across data stores. For examples, on data changes/access, we can publish notifications.
