### ISSUE TITLE
s3 catalog example

### ISSUE THREAD

**Issue by tooptoop4** [Netflix/metacat#291]
can you post s3 catalog example (not hive)? i couldn't see any with bucket path, access keys.etc I assume metacat can import object tags.

**Comment by ajoymajumdar** [comment]
No, s3 catalog is not a connector for s3 as a object store. In Metacat we created a simpler and faster version of the hive metastore data model to store metadata about the data stored. At Netflix, we store data in S3 and so we named it s3 connector.

**Comment by rae89** [comment]
So how do you use metacat with data the lives in s3?
