### ISSUE TITLE
Documentation / Discussion groups

### ISSUE THREAD

**Issue by dmoore247** [Netflix/metacat#81]
Are there any documents and/or discussion groups?

**Comment by ajoymajumdar** [comment]
Even though we made the project public, we did not officially open sourced it. The main reason for us to make it public was to share the code with other folks with similar interests. At present, other than the ReadMe, we do not have any other documentation published. We are planning to do so soon.
I have created a google group metacatoss. Please post your question there.

**Comment by satybald** [comment]
thanks for making project public. I've added a link to google group
https://groups.google.com/forum/#!forum/metacatoss
